In [1]:
import torch 

In [2]:
randint=torch.randint(-100,10,(6,))
print(randint)

tensor([ -5, -86, -80, -98,   4, -27])


In [3]:
tensor=torch.tensor([[-0.1,1.2],[2.2,3.1],[4.9,5.2]])
print(tensor)

tensor([[-0.1000,  1.2000],
        [ 2.2000,  3.1000],
        [ 4.9000,  5.2000]])


In [4]:
zeros=torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones=torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [6]:
input=torch.empty(2,3)
print(input)

tensor([[-2.2588e+33,  4.5018e-41, -2.2588e+33],
        [ 4.5018e-41,  4.4842e-44,  0.0000e+00]])


In [7]:
arange=torch.arange(5)
print(arange)

tensor([0, 1, 2, 3, 4])


In [8]:
linspace=torch.linspace(0,10,5)
print(linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [9]:
logspace=torch.logspace(0,10,5)
print(logspace)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])


In [10]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
empty_like=torch.empty_like(eye)
print(empty_like)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.0319e-43,  0.0000e+00,  1.4210e-22,  0.0000e+00, -2.2588e+33],
        [ 4.5018e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [14]:
import torch 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [15]:
import time 
start_time=time.time()
zeros=torch.zeros(1,1)
end_time=time.time()
elapsed_time=end_time-start_time
print(elapsed_time)

0.00039577484130859375


In [21]:
probabilities=torch.tensor([0.1,0.9])
samples=torch.multinomial(probabilities,10, replacement=True)
print(samples)


tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 1])


In [24]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5,6,7,8])),dim=0)
print(out)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


writing .py file in colab 

In [25]:
%%writefile my_script.py
def add(a, b):
    return a + b

if __name__ == "__main__":
    print(add(2, 3))


Writing my_script.py


In [ ]:
! python my_script.py


5


In [27]:
%%writefile /content/drive/MyDrive/test.py
print("saved in Drive")


Writing /content/drive/MyDrive/test.py


In [28]:
out=torch.tensor([1,2,3,4])
out=torch.cat((out,torch.tensor([5,6,7,8])),dim=0)
print(out)  

tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [29]:
out=torch.tril(torch.ones(5,5))
out 

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
out=torch.triu(torch.ones(5,5))
out 

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [33]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,1)
out

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [34]:
torch.exp(out)

tensor([[1.0000, 2.7183, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

In [35]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
print(out.shape)

torch.Size([4, 3, 2])


In [36]:
tensor1=torch.tensor([1,2,3,4])
tensor2=torch.tensor([5,6,7,8])
tensor3=torch.tensor([9,10,11,12])
out=torch.stack((tensor1,tensor2,tensor3),dim=0)
print(out)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
