In [1]:
import torch 

In [7]:
! nvidia-smi


/bin/bash: nvidia-smi: command not found


In [2]:
randint=torch.randint(-100,10,(6,))
print(randint)

tensor([-100,  -12,  -42,  -70,  -19,  -81])


In [8]:
tensor=torch.tensor([[-0.1,1.2],[2.2,3.1],[4.9,5.2]])
print(tensor)

tensor([[-0.1000,  1.2000],
        [ 2.2000,  3.1000],
        [ 4.9000,  5.2000]])


In [9]:
zeros=torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones=torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
input=torch.empty(2,3)
print(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
arange=torch.arange(5)
print(arange)

tensor([0, 1, 2, 3, 4])


In [8]:
linspace=torch.linspace(0,10,5)
print(linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [9]:
logspace=torch.logspace(0,10,5)
print(logspace)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])


In [10]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
empty_like=torch.empty_like(eye)
print(empty_like)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.0319e-43,  0.0000e+00,  1.4210e-22,  0.0000e+00, -2.2588e+33],
        [ 4.5018e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [ ]:
import torch 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
import time 
start_time=time.time()
zeros=torch.zeros(1,1)
end_time=time.time()
elapsed_time=end_time-start_time
print(elapsed_time)

0.03261756896972656


In [21]:
probabilities=torch.tensor([0.1,0.9])
samples=torch.multinomial(probabilities,10, replacement=True)
print(samples)


tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 1])


In [24]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5,6,7,8])),dim=0)
print(out)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


writing .py file in colab 

In [25]:
%%writefile my_script.py
def add(a, b):
    return a + b

if __name__ == "__main__":
    print(add(2, 3))


Writing my_script.py


In [ ]:
! python my_script.py


5


In [27]:
%%writefile /content/drive/MyDrive/test.py
print("saved in Drive")


Writing /content/drive/MyDrive/test.py


In [28]:
out=torch.tensor([1,2,3,4])
out=torch.cat((out,torch.tensor([5,6,7,8])),dim=0)
print(out)  

tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [29]:
out=torch.tril(torch.ones(5,5))
out 

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
out=torch.triu(torch.ones(5,5))
out 

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [33]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,1)
out

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [34]:
torch.exp(out)

tensor([[1.0000, 2.7183, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 2.7183, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 2.7183, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 2.7183],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

In [35]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
print(out.shape)

torch.Size([4, 3, 2])


In [36]:
tensor1=torch.tensor([1,2,3,4])
tensor2=torch.tensor([5,6,7,8])
tensor3=torch.tensor([9,10,11,12])
out=torch.stack((tensor1,tensor2,tensor3),dim=0)
print(out)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [2]:
import torch
import torch.nn as nn 
sample=torch.tensor([1,2,3,4], dtype=torch.float32)
linear=nn.Linear(4,4,bias=False) # why bias is false?
output=linear(sample)
print(output)

tensor([ 1.4505,  2.1039, -2.7121,  0.9294], grad_fn=<SqueezeBackward4>)


In [3]:
import torch.nn.functional as F 
tensor1=torch.tensor([1.0,2.0,3.0])
tensor2=F.softmax(tensor1,dim=0)
print(tensor2)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
vocab_size=10000
embedding_dim=300
embedding=nn.Embedding(vocab_size,embedding_dim)
input=torch.tensor([1,2,3,4])
output=embedding(input)
print(output)
print(output.shape) 

tensor([[ 2.1872,  0.2943,  0.4725,  ...,  0.5364,  1.4733, -0.3565],
        [ 0.9379,  0.4033,  0.5829,  ..., -1.0231, -0.2599,  0.2269],
        [ 0.9734, -1.1700, -1.1493,  ...,  1.1385,  0.8291, -2.0125],
        [ 1.0699, -0.6157, -0.6267,  ...,  0.7949, -0.7680,  0.6175]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 300])


In [7]:
a=torch.tensor([1,2,3,4])
a=a.unsqueeze(0)
print(a.shape)

torch.Size([1, 4])


In [12]:
print('hello world')

hello world


In [11]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

dot = np.dot(A,B)

print(dot)

32


In [5]:
int64=torch.tensor([[1,2],[3,4]], dtype=torch.int64)
float32=torch.rand(2,3).float()
result=torch.matmul(int64,float32)
print(result)

RuntimeError: expected m1 and m2 to have the same dtype, but got: long long != float

In [8]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.int64)
b = torch.rand(2, 3, dtype=torch.float32)

result = torch.matmul(a.float(), b)   # or: a.to(b.dtype)
print(result)


tensor([[1.7661, 1.8305, 0.7254],
        [3.9751, 4.0918, 1.4513]])


In [1]:
import torch

a=torch.rand(1,3,2).float()


X,Y,Z=a.shape
a.view(X,Y,Z)
print(X,Y,Z)

1 3 2


In [2]:

import torch.nn.functional as F
x=torch.tensor([-0.05],dtype=torch.float32)
y=F.softmax(x,dim=0)
print(y)

tensor([1.])


In [5]:
x=torch.tensor([1],dtype=torch.float32)
y=F.tanh(x)
print(y)

tensor([0.7616])
