In [1]:
import torch 

In [2]:
randint=torch.randint(-100,10,(6,))
print(randint)

tensor([-100,    9,    5,  -37,  -49,  -85])


In [4]:
tensor=torch.tensor([[-0.1,1.2],[2.2,3.1],[4.9,5.2]])
print(tensor)

tensor([[-0.1000,  1.2000],
        [ 2.2000,  3.1000],
        [ 4.9000,  5.2000]])


In [5]:
zeros=torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
ones=torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [7]:
input=torch.empty(2,3)
print(input)

tensor([[1.1146e-13, 4.4930e-41, 5.3734e-23],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [9]:
arange=torch.arange(5)
print(arange)

tensor([0, 1, 2, 3, 4])


In [10]:
linspace=torch.linspace(0,10,5)
print(linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [12]:
logspace=torch.logspace(0,10,5)
print(logspace)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])


In [13]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
empty_like=torch.empty_like(eye)
print(empty_like)

tensor([[0.0000e+00, 0.0000e+00, 2.6302e+20, 6.1949e-04, 6.4805e-10],
        [6.3014e-10, 1.6408e-07, 6.8738e-04, 6.9363e-07, 1.6967e-07],
        [6.4097e-10, 1.4580e-19, 1.1495e+24, 3.0956e-18, 6.0397e-07],
        [5.3978e-05, 1.2983e-11, 2.0805e+23, 3.4303e-06, 1.0779e-08],
        [1.9989e+20, 8.3567e+20, 5.3483e+22, 2.4286e-18, 3.1360e+27]])


In [17]:
import torch 
device = 'cuda' if torch.cuda_is_available() else 'cpu'

AttributeError: module 'torch' has no attribute 'cuda_is_available'