In [1]:
import torch 

In [2]:
randint=torch.randint(-100,10,(6,))
print(randint)

tensor([-100,    9,    5,  -37,  -49,  -85])


In [4]:
tensor=torch.tensor([[-0.1,1.2],[2.2,3.1],[4.9,5.2]])
print(tensor)

tensor([[-0.1000,  1.2000],
        [ 2.2000,  3.1000],
        [ 4.9000,  5.2000]])


In [5]:
zeros=torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
ones=torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [7]:
input=torch.empty(2,3)
print(input)

tensor([[1.1146e-13, 4.4930e-41, 5.3734e-23],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [9]:
arange=torch.arange(5)
print(arange)

tensor([0, 1, 2, 3, 4])


In [10]:
linspace=torch.linspace(0,10,5)
print(linspace)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
