In [2]:
import torch 
import torch.nn as nn
import torch.nn.functional as F 
import math

toy dataset 

In [3]:
sentences = [
    ["I", "love", "AI"],
    ["AI", "learns", "fast"],
    ["You", "love", "Python"]
]

vocab = {
    "<PAD>": 0,
    "I": 1,
    "love": 2,
    "AI": 3,
    "learns": 4,
    "fast": 5,
    "You": 6,
    "Python": 7
}


encode

In [4]:
encoded=[]

In [5]:
for sentence in sentences:
       ids=[vocab[word] for word in sentence]
       encoded.append(ids)
x_ids=torch.tensor(encoded)

In [6]:
print(x_ids)
print(x_ids.shape)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 2, 7]])
torch.Size([3, 3])


torch size niba batch size er jonno 

In [8]:
vocab_size=len(vocab)
embed_dim=8
embedding=nn.Embedding(vocab_size, embed_dim)
x=embedding(x_ids)
print(x.shape)


torch.Size([3, 3, 8])


In [11]:
class selfHeadAttention(nn.Module):
       def __init__(self,embed_dim):
              super().__init__()
              self.embed_dim=embed_dim

              self.W_q=nn.Linear(embed_dim,embed_dim)
              self.W_k=nn.Linear(embed_dim,embed_dim)
              self.W_v=nn.Linear(embed_dim,embed_dim)
       def forward(self,x):
              Q=self.W_q(x)
              K=self.W_k(x)
              V=self.W_v(x)

              scores=torch.matmul(Q,K.transpose(-2,-1))/math.sqrt(self.embed_dim)
              attention_weights=F.softmax(scores,dim=-1)
              output=torch.matmul(attention_weights,V)

              return output, attention_weights



In [12]:
single_head=selfHeadAttention(embed_dim)
self_head_output,self_weights=single_head(x)
print("Single Head Output Shape:", self_head_output.shape)
print("Attention Weights Shape:", self_weights.shape)
print(self_weights)

Single Head Output Shape: torch.Size([3, 3, 8])
Attention Weights Shape: torch.Size([3, 3, 3])
tensor([[[0.3257, 0.3390, 0.3353],
         [0.3399, 0.3123, 0.3479],
         [0.3633, 0.3191, 0.3177]],

        [[0.3039, 0.3892, 0.3069],
         [0.3247, 0.5198, 0.1554],
         [0.2990, 0.3972, 0.3038]],

        [[0.3571, 0.2965, 0.3464],
         [0.3840, 0.3808, 0.2352],
         [0.4832, 0.3522, 0.1646]]], grad_fn=<SoftmaxBackward0>)


In [13]:
single_head=selfHeadAttention(embed_dim)
single_output,self_weights=single_head(x)
print("Single Head Output Shape:", single_output.shape)
print("Attention Weights Shape:", self_weights.shape)
print(self_weights)

Single Head Output Shape: torch.Size([3, 3, 8])
Attention Weights Shape: torch.Size([3, 3, 3])
tensor([[[0.1902, 0.4685, 0.3413],
         [0.4155, 0.1967, 0.3878],
         [0.3871, 0.2834, 0.3295]],

        [[0.3410, 0.2672, 0.3918],
         [0.4454, 0.2285, 0.3261],
         [0.2618, 0.5577, 0.1805]],

        [[0.3511, 0.3330, 0.3159],
         [0.4988, 0.1950, 0.3062],
         [0.6830, 0.1206, 0.1964]]], grad_fn=<SoftmaxBackward0>)
